[graph]
all-features = true

[advisories]
yanked = "deny"

[licenses]
confidence-threshold = 0.8
allow = ["Apache-2.0", "ISC", "MIT", "Unicode-3.0"]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
