version = 1

[typescript_go]
path = "ref/typescript-go"
repository = "https://github.com/microsoft/typescript-go.git"
commit = "1de8d68230f8759af6fb71d9cf0f9c37d2c65507"
tree = "9a665b368b821119d74ef17c0e5c7b97893252b4"
committer_date = "2026-04-17T21:50:24Z"
author = "Anders Hejlsberg"
subject = "Exports aliases for CJS `exports.Foo = ...` assignments when appropriate (#3431)"
